# Generated by Django 4.2.16 on 2025-11-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderform', '0002_seed_checlist_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='category',
            field=models.CharField(choices=[('STANDARD_KIT', 'Standard Kit'), ('PAYLOAD', 'Payload'), ('GCS', 'Ground Control Station'), ('ACCESSORIES', 'Accessories'), ('SOFTWARE', 'Software'), ('FIELD_TRAINING', 'Field Training'), ('RPC_PROGRAM', 'RPC Program')], max_length=50),
        ),
    ]
