# Generated by Django 4.2.16 on 2025-11-19 07:21

import backend_app.orderform.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderform', '0003_alter_checklistitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=backend_app.orderform.models.today_local),
        ),
    ]
