# Generated by Django 4.2.16 on 2025-11-20 06:45

import backend_app.orderform.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderform', '0004_alter_order_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDeliveryInfo',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='delivery_info', serialize=False, to='orderform.order')),
                ('manufacturer_attachment', models.FileField(blank=True, null=True, upload_to=backend_app.orderform.models.manufacturer_upload_to)),
                ('testing_attachment', models.FileField(blank=True, null=True, upload_to=backend_app.orderform.models.testing_upload_to)),
                ('uin_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('ready_for_delivery', models.BooleanField(default=False)),
            ],
        ),
    ]
