# Generated by Django 4.2.16 on 2025-11-20 10:33

import backend_app.orderform.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderform', '0005_orderdeliveryinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdeliveryinfo',
            name='manufacturer_attachment',
        ),
        migrations.RemoveField(
            model_name='orderdeliveryinfo',
            name='testing_attachment',
        ),
        migrations.CreateModel(
            name='OrderDeliveryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('MANUFACTURER', 'Manufacturer'), ('TESTING', 'Testing')], max_length=20)),
                ('file', models.FileField(upload_to=backend_app.orderform.models.delivery_attachment_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orderform.orderdeliveryinfo')),
            ],
        ),
    ]
