# Generated by Django 4.2.16 on 2025-11-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderform', '0006_remove_orderdeliveryinfo_manufacturer_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('MANUFACTURING', 'Manufacturing'), ('TESTING', 'Testing'), ('READY FOR DELIVERY', 'Ready for delivery')], default='REQUESTED', max_length=20),
        ),
    ]
